server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://101.132.140.132/blog?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    ip: 101.132.140.132
    port: 3306
    database: blog

  thymeleaf:
    cache: false
    check-template: false
    mode: LEGACYHTML5

  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yannyao.blog.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

com:
  yannyao:
    custom:
      windows-path: d:/yannyao
      linux-path: /yannyao

